config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Defines the root path route ("/")
  root "home#index"

  # Defines the section path route ("/")
  get '/section/:sectionId', to: 'section#index', as: 'section'

  # Defines the article path route ("/")
  get '/section/:sectionId/article/:articleId', to: 'article#index', as: 'article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_controller.rb
require 'buttercms-ruby'
ButterCMS::api_token = ENV["BUTTER_API_TOKEN"]

class ArticleController < ApplicationController
  def index
    sectionParamsValue = params[:sectionId]
    articleParamsValue = params[:articleId]
    p params
    
    articleData = ButterCMS::Page.get('*', articleParamsValue)
    @articleData = articleData.data
    p articleData.data
  rescue ActionView::Template::Error => e
    raise ButterCmsError::MissingComponentPartial, e
  end

  def not_found
    render '404', layout: false
  end
end

app/controllers/home_controller.rb
require 'buttercms-ruby'
ButterCMS::api_token = ENV["BUTTER_API_TOKEN"]

class HomeController < ApplicationController
  def search()
    search = params[:query]
    p search
    if search
      listData = ButterCMS::Page.search(search, {
        page_type: 'kb_article_type'
      });

      if listData.items.empty?
        # Do something if my_array is empty
        listData = ButterCMS::Page.search(search, {
          page_type: 'kb_section_type'
        });
        # @listData = listData
        if listData.items.empty?
          redirect_to '/section/' + 'not-found'
          session[:queryValue] = search
        else
          redirect_to '/section/' + listData.items[0].data.slug
        end
      else
        # Do something if my_array is not empty
        @listData = listData.items
      end

      p listData

     else
      @listData = []
    end
  end
  
  def index
    homeData = ButterCMS::Page.get('*', "kb-homepage")
    @homeData = homeData.data
    # p homeData.data

    search()

    rescue ActionView::Template::Error => e
      raise ButterCmsError::MissingComponentPartial, e
  end


  def not_found
    render '404', layout: false
  end
end

app/controllers/section_controller.rb
require 'buttercms-ruby'
ButterCMS::api_token = ENV["BUTTER_API_TOKEN"]

class SectionController < ApplicationController
  def index
    ## get homepage
    homeData = ButterCMS::Page.get('*', "kb-homepage")
    @homeData = homeData.data
    # p homeData.data

    ## get section
    sectionParamsValue = params[:sectionId]
    query = params[:params]
    if sectionParamsValue != 'not-found'
      sectionData = ButterCMS::Page.get('*', sectionParamsValue)
      @sectionData = sectionData.data
      @sectionParamsValue = sectionParamsValue
      # p sectionData.data
    else
      @query = session[:queryValue]
      @sectionData = nil
      # p sectionData
    end

    p params
    p sectionParamsValue

  rescue ActionView::Template::Error => e
    raise ButterCmsError::MissingComponentPartial, e
  end

  def not_found
    render '404', layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/helpers/view_helper.rb
module ViewHelper
end

app/views/article/index.html.erb
<div class="max-w-[1250px] py-2 mx-auto">
    <%= @articleData.fields.article_body.html_safe %>
</div>

app/views/home/index.html.erb
<div>
    <div id="docsSearch">
        <h1>
        <%= @homeData.fields.kb_home_title %>
        </h1>

        <form action="/" method="GET" id="searchBar" autocomplete="off" class="md:w-[635px] mx-auto">
            <div class="w-full md:flex md:items-center md:justify-center -mx-2">
                <div class="md:w-[460px] px-2">
                    <input type="text" 
                        name="query" 
                        title="search-query" 
                        class="search-query block" 
                        placeholder="Search Beacon, Docs, Reports, etc" 
                        aria-label="Search Beacon, Docs, Reports, etc" value=""
                    >
                </div>

                <div class="md:w-4/12 px-2">
                    <button 
                        type="submit" 
                        aria-label="Search"
                        class="block" 
                    >
                        <i class="icon-search lp"></i>
                        <span>Search</span>
                    </button>
                </div>
            </div>

            <% if @listData %>
                <div id="serp-dd" class="mt-4">
                    <ul class="result">
                        <% @listData.each do |article| %>
                        <li>
                            <%= link_to article_path(article.slug, article.slug)  do%>
                                <%= article.name %>
                            <% end %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        </form>
    </div>


    <section id="contentArea" class="cont-fluid container mx-auto">
        <div id="noResults" style="display:none;">No results found</div>
        <section class="collection-category" id="collection-category-1">
            <h2 id="collection-1">
                <a>
                 <%= @homeData.fields.kb_home_sections[0].kb_section_title %>
                </a>
            </h2>
            <section class="flex flex-wrap category-list">
                
                <% @homeData.fields.kb_home_sections[0].kb_sections.each do |section| %>
                    <div class="p-3 w-full md:w-6/12 lg:w-4/12">
                        <%= link_to section_path(section.slug)  do%>
                            <div class="category" id="<%= section.slug %>" style="background-image: url(<%= section.fields.kb_section_article_image %>)">
                                <h3>
                                    <%= section.fields.kb_section_name %>
                                </h3>
                                <p>
                                    <%= section.fields.kb_section_description %>
                                </p>
                                <p class="article-count">                                    
                                    <span class="notranslate">
                                        <%= section.fields.kb_section_article_type.length() %>
                                    </span> 
                                    articles                                     
                                </p>         
                            </div>
                        <% end %>
                    </div>
                <% end %>

            </section>
        </section>
        
        <section class="collection-category" id="collection-category-1202">
            <h2 id="collection-1202">
                <a>
                 <%= @homeData.fields.kb_home_sections[1].kb_section_title %>
                </a>
            </h2>

            <section class="flex flex-wrap category-list ">
                <% @homeData.fields.kb_home_sections[1].kb_sections.each do |section| %>
                    <div class="p-3 w-full md:w-6/12 lg:w-4/12">
                        <%= link_to section_path(section.slug)  do%>
                            <div class="category" id="<%= section.slug %>" style="background-image: url(<%= section.fields.kb_section_article_image %>)">
                                <h3>
                                    <%= section.fields.kb_section_name %>
                                </h3>
                                <p>
                                    <%= section.fields.kb_section_description %>
                                </p>
                                <p class="article-count">                                    
                                    <span class="notranslate">
                                        <%= section.fields.kb_section_article_type.length() %>
                                    </span> 
                                    articles                                     
                                </p>         
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </section>
        </section>
        
        <section class="collection-category" id="collection-category-3">
            <h2 id="collection-3">
                <a>
                 <%= @homeData.fields.kb_home_sections[2].kb_section_title %>
                </a>
            </h2>

            <section class="category-list flex flex-wrap">
                <% @homeData.fields.kb_home_sections[2].kb_sections.each do |section| %>
                    <div class="p-3 w-full md:w-6/12 lg:w-4/12">
                        <%= link_to section_path(section.slug)  do%>
                            <div class="category" id="<%= section.slug %>" style="background-image: url(<%= section.fields.kb_section_article_image %>)">
                                <h3>
                                    <%= section.fields.kb_section_name %>
                                </h3>
                                <p>
                                    <%= section.fields.kb_section_description %>
                                </p>
                                <p class="article-count">                                    
                                    <span class="notranslate">
                                        <%= section.fields.kb_section_article_type.length() %>
                                    </span> 
                                    articles                                     
                                </p>         
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </section>
        </section>

        <footer class="center">
            <p>
                ©<a href="https://www.helpscout.com/">Help Scout</a>
                2023. 
                <span>
                    Powered by 
                    <a rel="nofollow noopener noreferrer" href="https://www.helpscout.com/knowledge-base/?utm_source=docs&amp;utm_medium=footerlink&amp;utm_campaign=Docs+Branding" target="_blank">
                    Help Scout
                    </a>
                </span>
            </p>
        </footer>
    </section>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <main class="">
      <div class="bg-[#404996] p-5 relative">
        <div class="max-w-[1250px] py-2 mx-auto flex items-center justify-between w-full">
          <div class="">
            <a class="brand block" href="/">
              <span>Help Scout Support</span>
            </a>
          </div>

          <div class="">
            <div class="block md:hidden">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </div>

            <div class="hidden md:flex navbar-links items-center -mx-6">
              <div id="home" class="px-6">
                  <a href="/">Home <b class="caret"></b></a>
              </div>
              <div id="help-desk" class="px-6">
                  <a href="/collection/1-help-desk">Help Desk  <b class="caret"></b></a>
              </div>
              <div id="beacon" class="px-6">
                  <a href="/collection/1202-beacon">Beacon  <b class="caret"></b></a>
              </div>
              <div id="docs" class="px-6">
                  <a href="/collection/3-docs">Docs  <b class="caret"></b></a>
              </div>
              <div id="status" class="px-6">
                  <a href="/collection/1454-status">Status  <b class="caret"></b></a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/section/index.html.erb
<div>
    <section id="contentArea" class="container-fluid max-w-[1250px] mx-auto">
        <div class="row-fluid">
            <section id="main-content" class="span9">
                <div class="contentWrapper">    
                    <hgroup id="categoryHead">
                        <% if @sectionData %>
                            <h1>
                                <%= @sectionData.fields.kb_section_name %>
                            </h1>
                            <p class="descrip">
                                <%= @sectionData.fields.kb_section_description %>
                            </p>
                        <% else %>
                            <h1>
                                Here's what we found for <%= @query %>
                            </h1>
                        <% end %>

                        <div class="sort">   
                            <form action="/category/832-getting-started" method="GET">
                                <select name="sort" id="sortBy" title="sort-by" onchange="this.form.submit();" aria-label="Page reloads on selection">
                                    <option value="">Sort by Default</option>
                                    <option value="name">Sort A-Z</option>
                                    <option value="popularity">Sort by Popularity</option>
                                    <option value="updatedAt">Sort by Last Updated</option>
                                </select>
                            </form>
                        </div>
                    </hgroup><!--/categoryHead-->

                    <% if @sectionData %>
                        <% @sectionData.fields.kb_section_article_type.each do |article| %>
                            <ul class="articleList">
                                <li>
                                    <%= link_to article_path(@sectionParamsValue, article.name) do%>
                                        <i class="icon-article-doc"></i>
                                        <span>
                                            <%= article.fields.article_description %>
                                        </span>   
                                    <% end %>
                                </li>
                            </ul>
                        <% end %>
                    <% else %>
                        <ul class="articleList">
                            <li>
                                No articles were found. Feel free to try again or contact us.
                            </li>
                        </ul>
                    <% end %>


                    
                </div><!--/contentWrapper-->
            </section><!--/content-->

            <aside id="sidebar" class="span3">
                <form action="/" method="GET" id="searchBar" class="sm" autocomplete="off">
                    <input type="hidden" name="collectionId">
                    <input type="text" name="query" title="search-query" class="search-query" placeholder="Search" value="" aria-label="Search">
                    <button type="submit">
                        <span class="sr-only">Toggle Search</span>
                        <i class="icon-search"></i>
                    </button>
                    <div id="serp-dd" style="display: none;" class="sb">
                        <ul class="result">
                        </ul>
                    </div>
                </form>

                
                <h3>Categories</h3>
                <ul class="nav nav-list">
                    <li class="active">
                        <a href="/category/832-getting-started">Getting Started  <i class="icon-arrow"></i></a>
                    </li>         
                    <li><a>Account Management  <i class="icon-arrow"></i></a></li>
                    <li><a >Reporting  <i class="icon-arrow"></i></a></li>
                    <li><a >Copying Email to Help Scout  <i class="icon-arrow"></i></a></li>
                    <li><a >Working with Conversations  <i class="icon-arrow"></i></a></li>
                    <li><a >Productivity  <i class="icon-arrow"></i></a></li>
                    <li><a >Mailbox and User Settings  <i class="icon-arrow"></i></a></li>
                    <li><a >Mobile Apps  <i class="icon-arrow"></i></a></li>
                    <li><a >Integrations  <i class="icon-arrow"></i></a></li>
                </ul>
                
            </aside><!--/span-->
        </div><!--/row-->
            
        <div id="noResults" style="display:none;">No results found</div>
        
        <%# <footer>
            <p>©
                <a href="https://www.helpscout.com/">Help Scout</a> 2023. 
                <span>
                    Powered by 
                    <a rel="nofollow noopener noreferrer" href="https://www.helpscout.com/knowledge-base/?utm_source=docs&amp;utm_medium=footerlink&amp;utm_campaign=Docs+Branding" target="_blank">
                        Help Scout
                    </a>
                </span>
            </p>
        </footer> %>
    </section>
</div>